frr version 8.4_git
frr defaults traditional
hostname R-BR1
no ipv6 forwarding
!
interface eth0
 ip address 172.16.3.6/30
 ip ospf network point-to-point
exit
!
interface lo
 ip address 1.1.1.2/32
exit
!
router bgp 65002
 bgp router-id 1.1.1.2
 neighbor 1.1.1.120 remote-as 65000
 neighbor 1.1.1.120 ebgp-multihop 5
 neighbor 1.1.1.120 update-source lo
 !
 address-family ipv4 unicast
  network 10.2.0.0/24
 exit-address-family
exit
!
router ospf
 ospf router-id 1.1.1.2
 network 1.1.1.2/32 area 2
 network 10.2.0.0/24 area 2
 network 172.16.3.4/30 area 2
exit
!
