frr version 8.4_git
frr defaults traditional
hostname PE2
no ipv6 forwarding
!
interface eth1
 ip address 172.16.0.9/30
 ip ospf network point-to-point
exit
!
interface eth2
 ip address 172.16.1.5/30
 ip ospf network point-to-point
exit
!
interface eth3
 ip address 172.16.2.1/30
 ip ospf network point-to-point
exit
!
interface lo
 ip address 1.1.1.111/32
exit
!
router bgp 65000
 bgp router-id 1.1.1.111
 neighbor 1.1.1.100 remote-as 65000
 neighbor 1.1.1.100 update-source lo
 neighbor 1.1.1.101 remote-as 65000
 neighbor 1.1.1.101 update-source lo
exit
!
router ospf
 ospf router-id 1.1.1.111
 network 1.1.1.111/32 area 0
 network 172.16.0.8/30 area 0
 network 172.16.1.4/30 area 0
 network 172.16.2.0/30 area 0
exit
!
