frr version 8.4_git
frr defaults traditional
hostname ABR-2
no ipv6 forwarding
!
interface eth1
 ip address 172.16.1.6/30
 ip ospf network point-to-point
exit
!
interface eth2
 ip address 172.16.4.1/30
 ip ospf network point-to-point
exit
!
interface eth3
 ip address 172.16.4.5/30
 ip ospf network point-to-point
exit
!
interface lo
 ip address 1.1.1.121/32
exit
!
router ospf
 ospf router-id 1.1.1.121
 network 1.1.1.121/32 area 0
 network 172.16.1.4/30 area 0
 network 172.16.4.0/30 area 3
 network 172.16.4.4/30 area 4
 area 3 stub
 area 3 range 10.3.0.0/23
 area 4 nssa 
 area 4 range 10.4.0.0/23
exit
!
