frr version 8.4_git
frr defaults traditional
hostname R-CLOUD
no ipv6 forwarding
!
interface eth0
 ip address 172.16.2.2/30
 ip ospf network point-to-point
exit
!
interface lo
 ip address 1.1.1.200/32
exit
!
router bgp 65100
 bgp router-id 1.1.1.200
 neighbor 1.1.1.111 remote-as 65000
 neighbor 1.1.1.111 ebgp-multihop 5
 neighbor 1.1.1.111 update-source lo
 !
 address-family ipv4 unicast
  network 10.100.1.0/24
  network 10.100.2.0/24
 exit-address-family
exit
!
