frr version 8.4_git
frr defaults traditional
hostname R-HQ
no ipv6 forwarding
!
interface eth0
 ip address 172.16.3.2/30
 ip ospf network point-to-point
exit
!
interface lo
 ip address 1.1.1.1/32
exit
!
router bgp 65001
 bgp router-id 1.1.1.1
 neighbor 1.1.1.120 remote-as 65000
 neighbor 1.1.1.120 ebgp-multihop 5
 neighbor 1.1.1.120 update-source lo
 !
 address-family ipv4 unicast
  network 10.1.0.0/24
 exit-address-family
exit
!
router ospf
 ospf router-id 1.1.1.1
 network 1.1.1.1/32 area 1
 network 10.1.0.0/24 area 1
 network 172.16.3.0/30 area 1
exit
!
