frr version 8.4_git
frr defaults traditional
hostname R-BR3
no ipv6 forwarding
!
interface eth0
 ip address 172.16.4.6/30
 ip ospf network point-to-point
exit
!
interface lo
 ip address 1.1.1.4/32
exit
!
router bgp 65004
 bgp router-id 1.1.1.4
 neighbor 1.1.1.121 remote-as 65000
 neighbor 1.1.1.121 ebgp-multihop 5
 neighbor 1.1.1.121 update-source lo
 !
 address-family ipv4 unicast
  network 10.4.0.0/24
 exit-address-family
exit
!
router ospf
 ospf router-id 1.1.1.4
 network 1.1.1.4/32 area 4
 network 10.4.0.0/24 area 4
 network 172.16.4.4/30 area 4
 area 4 nssa 
exit
!
