Building configuration...

Current configuration:
!
frr version 8.4_git
frr defaults traditional
hostname P1-CORE
no ipv6 forwarding
!
interface eth0
 ip address 172.16.0.1/30
 ip ospf network point-to-point
exit
!
interface lo
 ip address 1.1.1.100/32
exit
!
router bgp 65000
 bgp router-id 1.1.1.100
 neighbor 1.1.1.101 remote-as 65000
 neighbor 1.1.1.101 update-source lo
 !
 address-family ipv4 unicast
  neighbor 1.1.1.101 next-hop-self
 exit-address-family
exit
!
router ospf
 ospf router-id 1.1.1.100
 network 1.1.1.100/32 area 0
 network 172.16.0.0/30 area 0
exit
!
end
